# Generated by Django 5.1.6 on 2025-02-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood_hockey_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.CharField(max_length=80)),
                ('test2', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='TestTable',
        ),
    ]
