# Generated by Django 5.1.6 on 2025-02-19 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood_hockey_app', '0004_games'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Games',
        ),
    ]
