# Generated by Django 5.1.7 on 2025-04-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood_hockey_app', '0006_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='Date',
            field=models.DateField(),
        ),
    ]
