# Generated by Django 5.1.7 on 2025-04-06 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood_hockey_app', '0007_alter_games_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='author',
        ),
    ]
