import React from "react";
import "../styles/Games.css";

function Game({ game, onDelete }) {
    return (
        <div className="game-container">
            <p className="game-date">{game.date}</p>
            <p className="game-opponent">{game.opponent}</p>
            <p className="game-scoreHC">{game.scoreHC}</p>
            <p className="game-scoreOpp">{game.scoreOpp}</p>
            <p className="game-goals">{game.goals}</p>
            <p className="game-penalties">{game.penalties}</p>
            <p className="game-penaltiesDrawn">{game.penaltiesDrawn}</p>
            <p className="game-penaltyTimeMin">{game.penaltyTimeMin}</p>
            <p className="game-penaltyTimeSec">{game.penaltyTimeSec}</p>
            <p className="game-faceoffs">{game.faceoffs}</p>
            <p className="game-faceoffsWon">{game.faceoffsWon}</p>
            <p className="game-faceoffWinPercentage">{game.faceoffWinPercentage}</p>
            <p className="game-hits">{game.hits}</p>
            <p className="game-faceoffsDZ">{game.faceoffsDZ}</p>
            <p className="game-faceoffsWonDZ">{game.faceoffsWonDZ}</p>
            <p className="game-faceoffsWonDZPercentage">{game.faceoffsWonDZPercentage}</p>
            <p className="game-faceoffsNZ">{game.faceoffsNZ}</p>
            <p className="game-faceoffsWonNZ">{game.faceoffsWonNZ}</p>
            <p className="game-faceoffsWonNZPercentage">{game.faceoffsWonNZPercentage}</p>
            <p className="game-faceoffsOZ">{game.faceoffsOZ}</p>
            <p className="game-faceoffsWonOZ">{game.faceoffsWonOZ}</p>
            <p className="game-faceoffsWonOZPercentage">{game.faceoffsWonOZPercentage}</p>
            <p className="game-blockedShots">{game.blockedShots}</p>
            <p className="game-faceoffsLost">{game.faceoffsLost}</p>
            <p className="game-scoringChances">{game.scoringChances}</p>
            <p className="game-corsiPercentage">{game.corsiPercentage}</p>
            <p className="game-hitsAgainst">{game.hitsAgainst}</p>
            <p className="game-powerPlay">{game.powerPlay}</p>
            <p className="game-successfulPowerPlay">{game.successfulPowerPlay}</p>
            <p className="game-powerPlayMin">{game.powerPlayMin}</p>
            <p className="game-powerPlaySec">{game.powerPlaySec}</p>
            <p className="game-powerPlayPercentage">{game.powerPlayPercentage}</p>
            <p className="game-shortHanded">{game.shortHanded}</p>
            <p className="game-penaltyKilling">{game.penaltyKilling}</p>
            <p className="game-shortHandedMin">{game.shortHandedMin}</p>
            <p className="game-shortHandedSec">{game.shortHandedSec}</p>
            <p className="game-shortHandedPercentage">{game.shortHandedPercentage}</p>
            <p className="game-xGPerShot">{game.xGPerShot}</p>
            <p className="game-opponentsXGPerShot">{game.opponentsXGPerShot}</p>
            <p className="game-netXG">{game.netXG}</p>
            <p className="game-xGConversion">{game.xGConversion}</p>
            <p className="game-xG">{game.xG}</p>
            <p className="game-opponentXG">{game.opponentXG}</p>
            <p className="game-xGPerGoal">{game.xGPerGoal}</p>
            <p className="game-shots">{game.shots}</p>
            <p className="game-shotsOnGoal">{game.shotsOnGoal}</p>
            <p className="game-shotsBlocking">{game.shotsBlocking}</p>
            <p className="game-missedShots">{game.missedShots}</p>
            <p className="game-percentageShotsOnGoal">{game.percentageShotsOnGoal}</p>
            <p className="game-slapshot">{game.slapshot}</p>
            <p className="game-wristShot">{game.wristShot}</p>
            <p className="game-powerPlayShots">{game.powerPlayShots}</p>
            <p className="game-shortHandedShots">{game.shortHandedShots}</p>
            <p className="game-shootoutsScored">{game.shootoutsScored}</p>
            <p className="game-offensivePlayMin">{game.offensivePlayMin}</p>
            <p className="game-offensivePlaySec">{game.offensivePlaySec}</p>
            <p className="game-defensivePlayMin">{game.defensivePlayMin}</p>
            <p className="game-defensivePlaySec">{game.defensivePlaySec}</p>
            <p className="game-ozPossessionMin">{game.ozPossessionMin}</p>
            <p className="game-ozPossessionSec">{game.ozPossessionSec}</p>
            <p className="game-nzPossessionMin">{game.nzPossessionMin}</p>
            <p className="game-nzPossessionSec">{game.nzPossessionSec}</p>
            <p className="game-dzPossessionMin">{game.dzPossessionMin}</p>
            <p className="game-dzPossessionSec">{game.dzPossessionSec}</p>
            <p className="game-puckBattles">{game.puckBattles}</p>
            <p className="game-puckBattlesWon">{game.puckBattlesWon}</p>
            <p className="game-puckBattlesWonPercentage">{game.puckBattlesWonPercentage}</p>
            <p className="game-puckBattlesOZ">{game.puckBattlesOZ}</p>
            <p className="game-puckBattlesNZ">{game.puckBattlesNZ}</p>
            <p className="game-puckBattlesDZ">{game.puckBattlesDZ}</p>
            <p className="game-dekes">{game.dekes}</p>
            <p className="game-dekesSuccessful">{game.dekesSuccessful}</p>
            <p className="game-dekesUnsuccessful">{game.dekesUnsuccessful}</p>
            <p className="game-dekesSuccessfulPercentage">{game.dekesSuccessfulPercentage}</p>
            <p className="game-passesTotal">{game.passesTotal}</p>
            <p className="game-accuratePasses">{game.accuratePasses}</p>
            <p className="game-accuratePassesPercentage">{game.accuratePassesPercentage}</p>
            <p className="game-preShotPasses">{game.preShotPasses}</p>
            <p className="game-dumpIns">{game.dumpIns}</p>
            <p className="game-dumpOuts">{game.dumpOuts}</p>
            <p className="game-passesToTheSlot">{game.passesToTheSlot}</p>
            <p className="game-ozPlay">{game.ozPlay}</p>
            <p className="game-ozPlayWithShots">{game.ozPlayWithShots}</p>
            <p className="game-ozPlayWithShotsPercentage">{game.ozPlayWithShotsPercentage}</p>
            <p className="game-counterAttacks">{game.counterAttacks}</p>
            <p className="game-counterAttackWithShots">{game.counterAttackWithShots}</p>
            <p className="game-counterAttackWithShotsPercentage">{game.counterAttackWithShotsPercentage}</p>
            <p className="game-takeaways">{game.takeaways}</p>
            <p className="game-takeawaysInNZ">{game.takeawaysInNZ}</p>
            <p className="game-takeawaysInDZ">{game.takeawaysInDZ}</p>
            <p className="game-puckLosses">{game.puckLosses}</p>
            <p className="game-puckLossesOZ">{game.puckLossesOZ}</p>
            <p className="game-puckLossesNZ">{game.puckLossesNZ}</p>
            <p className="game-puckLossesDZ">{game.puckLossesDZ}</p>
            <p className="game-retrievals">{game.retrievals}</p>
            <p className="game-powerPlayRetrievals">{game.powerPlayRetrievals}</p>
            <p className="game-penaltyKillRetrievals">{game.penaltyKillRetrievals}</p>
            <p className="game-evOzRetrievals">{game.evOzRetrievals}</p>
            <p className="game-evDzRetrievals">{game.evDzRetrievals}</p>
            <p className="game-takeawaysInOZ">{game.takeawaysInOZ}</p>
            <p className="game-loosePuckRecovery">{game.loosePuckRecovery}</p>
            <p className="game-opponentDumpInRetrievals">{game.opponentDumpInRetrievals}</p>
            <p className="game-entries">{game.entries}</p>
            <p className="game-entriesViaPass">{game.entriesViaPass}</p>
            <p className="game-entriesViaDumpIn">{game.entriesViaDumpIn}</p>
            <p className="game-entriesViaStickhandling">{game.entriesViaStickhandling}</p>
            <p className="game-breakouts">{game.breakouts}</p>
            <p className="game-breakoutsViaPass">{game.breakoutsViaPass}</p>
            <p className="game-breakoutsViaDumpOut">{game.breakoutsViaDumpOut}</p>
            <p className="game-breakoutsViaStickhandling">{game.breakoutsViaStickhandling}</p>
            <button className="delete-button" onClick={() => onDelete(game.id)}>
                Delete
            </button>
        </div>
    );
}

export default Game;
